server:
  port: 8010

spring:
  application:
    name: websocketServer

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 222.197.219.26:8848


