server:
  port: 8010

spring:
  application:
    name: websocketServer

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 222.197.219.26:8848

    stream:
      bindings:
        output:
          content-type: application/json
          destination: test
      rocketmq:
        binder:
          # 配置rocketmq的nameserver地址
          name-server: 222.197.219.26:9876
  redis:
    database: 0
    host: 222.197.219.26
    port: 6379
    password: 973158
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0



websocket:
  timeout-time: 600000



