server:
  port: 8012

spring:
  application:
    name: chineses-asr-backend

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 222.197.219.26:8848

    stream:
      bindings:
        transcription-zh-output:
          content-type: application/json
          destination: transcription-zh

        speech-zh-input:
          content-type: application/json
          destination: speech-zh
          group: speech-zh-group

      rocketmq:
        binder:
          # 配置rocketmq的nameserver地址
          name-server: 222.197.219.26:9876
        bindings:
          speech-zh-input: # 定义name为output的binding
            consumer:
              enabled: true # 是否开启消费，默认为 true
              broadcasting: false # 是否使用广播消费，默认为 false 使用集群消费，如果要使用广播消费值设成true。
              delayLevelWhenNextConsume: -1 # 不重复，直接放入死信队列
          transcription-zh-output:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              group: transcription-zh-group
              sync: false # 是否同步发送消息，默认为 false 异步。



management:
  endpoints:
    web:
      exposure:
        include: '*'


  endpoint:
    health:
      show-details: always
